# Generated by Django 5.1.4 on 2025-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comments_listings_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('home', 'home'), ('vehicles', 'vehicles'), ('fashion', 'fashion'), ('toys', 'toys'), ('eletronics', 'eletronics'), ('sports', 'sports'), ('food', 'food'), ('housing', 'housing'), ('varied', 'varied')], default='varied', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='img_is_url',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='data_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
