# Generated by Django 5.1.4 on 2025-02-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_category_listings_img_is_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
            preserve_default=False,
        ),
    ]
