# Generated by Django 5.1.4 on 2025-03-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='img_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='listings',
            name='img_is_url',
            field=models.BooleanField(default=False),
        ),
    ]
