# Generated by Django 5.1.4 on 2025-03-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_img_url_alter_listings_img_is_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='img_is_url',
            field=models.BooleanField(),
        ),
    ]
